"""
Summary Reporter - 通用摘要报告生成和发布工具

这个模块提供了一个通用的摘要报告系统，可以：
1. 收集各组件的运行统计数据
2. 生成格式化的 Markdown 摘要报告
3. 将摘要发布到指定的 GitHub Issue

使用示例：
    from libs.summary_reporter import SummaryReporter

    reporter = SummaryReporter()
    reporter.add_component_summary("join-issues", {...})
    reporter.add_component_summary("task-checker", {...})

    if reporter.is_enabled():
        reporter.post_to_issue(token)
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, Optional

from libs.utils import load_simple_yaml
from libs.github_client import post_summary_comment


class SummaryReporter:
    """
    通用摘要报告生成器和发布器
    """

    def __init__(self, config_path: Optional[str] = None):
        """
        初始化摘要报告器

        Args:
            config_path: 配置文件路径，如果为 None 则使用默认路径
        """
        if config_path is None:
            config_path = str(Path(__file__).parent.parent / "config" / "summary-config.yml")

        self.config = load_simple_yaml(config_path)
        self.summaries: Dict[str, Dict[str, Any]] = {}
        self.errors: list = []
        self.start_time = datetime.now()

    def is_enabled(self) -> bool:
        """
        检查摘要报告功能是否启用

        Returns:
            True 如果启用，False 如果禁用
        """
        return self.config.get("enabled", False)

    def add_component_summary(self, component_name: str, summary_data: Dict[str, Any]):
        """
        添加组件的摘要数据

        Args:
            component_name: 组件名称（例如 "join-issues", "task-checker"）
            summary_data: 组件的统计数据字典
        """
        self.summaries[component_name] = summary_data

    def add_error(self, error_msg: str):
        """
        添加错误信息到摘要

        Args:
            error_msg: 错误信息
        """
        self.errors.append(error_msg)

    def generate_report(self, verbose: bool = False) -> str:
        """
        生成 Markdown 格式的摘要报告

        Args:
            verbose: 是否包含详细信息

        Returns:
            Markdown 格式的摘要文本
        """
        lines = []

        # 标题和时间
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d %H:%M:%S UTC")
        title_template = self.config.get("title_template", "🤖 MCPP Bot 运行报告 - {date}")
        title = title_template.replace("{date}", date_str)

        lines.append(f"## {title}")
        lines.append(f"**运行时间:** {date_str}")
        lines.append("")

        # 错误摘要（如果有）
        if self.errors:
            lines.append("### ❌ 运行错误")
            for error in self.errors:
                lines.append(f"- {error}")
            lines.append("")

        # 各组件摘要
        include_details = self.config.get("include_details", True)

        if "join-issues" in self.summaries:
            lines.extend(self._format_join_issues_summary(self.summaries["join-issues"], include_details))

        if "task-checker" in self.summaries:
            lines.extend(self._format_task_checker_summary(self.summaries["task-checker"], include_details))

        # 页脚
        lines.append("---")
        lines.append("*Generated by [MCPP Bot](https://github.com/mcpp-community/mcpp-bot)*")

        return "\n".join(lines)

    def _format_join_issues_summary(self, summary: Dict[str, Any], include_details: bool) -> list:
        """
        格式化加入请求扫描器的摘要

        Args:
            summary: 摘要数据
            include_details: 是否包含详细信息

        Returns:
            格式化的文本行列表
        """
        lines = []
        lines.append("### 📋 加入请求扫描器 (Join Issues Scanner)")

        total = summary.get("total_issues", 0)
        completed = summary.get("completed", 0)
        skipped = summary.get("skipped", 0)
        not_member = summary.get("not_member_yet", 0)

        # 简要统计
        lines.append(f"- **待处理请求:** {total}")
        lines.append(f"- **已完成并关闭:** {completed} ✅")

        if include_details:
            lines.append(f"- **标题已更新:** {summary.get('title_updated', 0)}")
            lines.append(f"- **等待加入组织:** {not_member}")
            lines.append(f"  - 发送提醒: {summary.get('reminder_sent', 0)}")
            lines.append(f"- **已添加到团队:** {summary.get('team_added', 0)}")

            team_failed = summary.get("team_add_failed", 0)
            if team_failed > 0:
                lines.append(f"- **添加失败:** {team_failed} ⚠️")

            lines.append(f"- **跳过:** {skipped}")
        else:
            # 简化模式：只显示关键指标
            if not_member > 0:
                lines.append(f"- **等待加入组织:** {not_member} (已发送 {summary.get('reminder_sent', 0)} 条提醒)")
            if skipped > 0:
                lines.append(f"- **跳过:** {skipped}")

        lines.append("")
        return lines

    def _format_task_checker_summary(self, summary: Dict[str, Any], include_details: bool) -> list:
        """
        格式化任务检查器的摘要

        Args:
            summary: 摘要数据
            include_details: 是否包含详细信息

        Returns:
            格式化的文本行列表
        """
        lines = []
        lines.append("### ⏰ 任务检查器 (Task Checker)")

        total_issues = summary.get("total_issues", 0)
        checked_issues = summary.get("checked_issues", 0)
        reminders = summary.get("reminders_sent", 0)
        reminded_issues = summary.get("reminded_issues", [])

        # 跳过统计
        skipped_no_priority = summary.get("skipped_no_priority", 0)
        skipped_not_in_filter = summary.get("skipped_not_in_filter", 0)
        skipped_no_timeout_config = summary.get("skipped_no_timeout_config", 0)
        skipped_not_timeout = summary.get("skipped_not_timeout", 0)

        # 简要统计
        if "total_repos" in summary:
            lines.append(f"- **扫描仓库数:** {summary.get('total_repos', 0)}")

        lines.append(f"- **问题总数 (Task标签):** {total_issues}")
        lines.append(f"- **检查的问题 (有优先级):** {checked_issues}")
        lines.append(f"- **发送提醒:** {reminders} 📬")

        if include_details:
            # 详细的跳过原因统计
            total_skipped = skipped_no_priority + skipped_not_in_filter + skipped_no_timeout_config + skipped_not_timeout
            lines.append(f"- **跳过的问题:** {total_skipped}")
            if total_skipped > 0:
                if skipped_no_priority > 0:
                    lines.append(f"  - 未设置优先级 (无Project/标签): {skipped_no_priority}")
                if skipped_not_in_filter > 0:
                    lines.append(f"  - 优先级不在检查范围: {skipped_not_in_filter}")
                if skipped_no_timeout_config > 0:
                    lines.append(f"  - 优先级未配置超时: {skipped_no_timeout_config}")
                if skipped_not_timeout > 0:
                    lines.append(f"  - 未超时: {skipped_not_timeout}")
        else:
            # 简要模式只显示未设置优先级的数量
            if skipped_no_priority > 0:
                lines.append(f"- **跳过 (未设置优先级):** {skipped_no_priority}")

        # 按优先级分类显示发送提醒的 issues
        if reminded_issues:
            lines.append("")
            lines.append("#### 发送提醒的任务")

            # 按优先级分组
            issues_by_priority = {"P0": [], "P1": [], "P2": []}
            for issue_info in reminded_issues:
                priority = issue_info.get("priority", "P2")
                if priority in issues_by_priority:
                    issues_by_priority[priority].append(issue_info)

            # 显示每个优先级的 issues
            for priority in ["P0", "P1", "P2"]:
                issues = issues_by_priority[priority]
                if issues:
                    priority_emoji = {"P0": "🔴", "P1": "🟡", "P2": "🟢"}
                    lines.append(f"\n**{priority_emoji.get(priority, '⚪')} {priority} 级别任务** ({len(issues)} 个):")
                    for issue_info in issues:
                        issue_number = issue_info.get("issue_number")
                        title = issue_info.get("title", "")
                        url = issue_info.get("url", "")
                        hours = issue_info.get("hours_since_update", 0)

                        # 截断过长的标题
                        if len(title) > 60:
                            title = title[:57] + "..."

                        lines.append(f"- [#{issue_number}]({url}) {title} (已 {hours:.1f}h 未更新)")

        lines.append("")
        return lines

    def post_to_issue(self, token: Optional[str] = None, verbose: bool = False) -> bool:
        """
        将摘要报告发布到配置的 GitHub Issue

        Args:
            token: GitHub API token，如果为 None 则从环境变量读取
            verbose: 是否打印详细信息

        Returns:
            True 如果发布成功，False 如果失败或未配置
        """
        if not self.is_enabled():
            if verbose:
                print("⊘ 摘要报告功能已禁用")
            return False

        target_url = self.config.get("target_issue_url", "").strip()
        if not target_url:
            if verbose:
                print("⊘ 未配置 target_issue_url，跳过发布摘要")
            return False

        if token is None:
            token = os.environ.get("GH_TOKEN", "").strip()

        if not token:
            if verbose:
                print("✗ 未设置 GH_TOKEN，无法发布摘要")
            return False

        # 生成摘要
        summary_text = self.generate_report(verbose=verbose)

        if verbose:
            print("\n摘要内容:\n")
            print(summary_text)
            print()

        # 发布到 Issue
        success = post_summary_comment(token, target_url, summary_text)

        if success and verbose:
            print(f"✓ 摘要已发布到: {target_url}")
        elif not success and verbose:
            print(f"✗ 发布摘要失败")

        return success

    def get_summary_dict(self) -> Dict[str, Any]:
        """
        获取所有组件的摘要数据

        Returns:
            包含所有组件摘要的字典
        """
        return {
            "summaries": self.summaries,
            "errors": self.errors,
            "start_time": self.start_time.isoformat(),
        }

    def print_console_summary(self):
        """
        在控制台打印简要摘要
        """
        print("\n" + "=" * 60)
        print("运行摘要")
        print("=" * 60)

        for component, summary in self.summaries.items():
            print(f"\n{component}:")
            for key, value in summary.items():
                print(f"  {key}: {value}")

        if self.errors:
            print("\n错误:")
            for error in self.errors:
                print(f"  - {error}")


# 便捷函数
def create_reporter(config_path: Optional[str] = None) -> SummaryReporter:
    """
    创建一个新的摘要报告器实例

    Args:
        config_path: 配置文件路径

    Returns:
        SummaryReporter 实例
    """
    return SummaryReporter(config_path)
